apiVersion: v2
name: fastapi-memories-api
description: A Helm chart for deploying FastAPI Memories API and PostgreSQL database on Kubernetes / EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - python
  - postgresql
  - eks
