services:  
  fastapi:
    image: kasisubbarayudu/kashi-memories-api:1.0 
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgres #${DATABASE_HOSTNAME}
      - DB_PASSWD=postgres #${DATABASE_PASSWORD}
      - ACCESS_TOKEN_EXPIRY_PERIOD_IN_MINUTES=30 #${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres #${DATABASE_PASSWORD}
      - POSTGRES_DB=fastapi #${DATABASE_NAME}
      - POSTGRES_MULTIPLE_DATABASES=testingdb
    volumes:
      - postgres-db:/var/lib/postgresql/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-dbs.sh

volumes:
  postgres-db:
