apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-memories-api.fullname" . }}
  labels:
    {{- include "fastapi-memories-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastapi-memories-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fastapi-memories-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ if .Values.postgres.enabled }}"{{ include "fastapi-memories-api.fullname" . }}-postgres"{{ else }}"localhost"{{ end }}
            - name: DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: DB_PASSWD
              value: {{ .Values.postgres.password | quote }}
            - name: DB_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: ACCESS_TOKEN_EXPIRY_PERIOD_IN_MINUTES
              value: {{ .Values.env.accessTokenExpiry | quote }}
            - name: COGNITO_BACKEND
              value: {{ .Values.env.cognitoBackend | quote }}
            - name: COGNITO_REGION
              value: {{ .Values.env.cognitoRegion | quote }}
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
